BeerOverflow/BeerOverflow/Controllers/BeersController.cs
using AutoMapper;
using BeerOverflow.Data.Context;
using BeerOverflow.Data.Models;
using BeerOverflow.Models;
using BeerOverflow.Service.Contracts;
using BeerOverflow.Service.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeerOverflow.Controllers
{
    [Route("/[controller]")]
    public class BeersController : Controller
    {
        private readonly BeerOverflowContext _context;
        private readonly IMapper _mapper;
        private readonly IBeerService _service;
        private readonly IBeerReviewService _reviewService;
        private readonly IBreweryService _breweryService;
        private readonly IStyleService _styleService;
        private readonly ICountryService _countryService;
        private readonly IUserService _userService;
        private readonly UserManager<User> _userManager;


        public BeersController(BeerOverflowContext context, IBeerService service, IBeerReviewService reviewService, IMapper mapper,
            IBreweryService breweryService, IStyleService styleService, ICountryService countryService, UserManager<User> userManager,
            IUserService userService)
        {
            this._context = context;
            this._service = service;
            this._reviewService = reviewService;
            this._breweryService = breweryService;
            this._styleService = styleService;
            this._mapper = mapper;
            this._countryService = countryService;
            this._userService = userService;
            this._userManager = userManager;
        }

        // GET: Beers
        [HttpGet("/List")]
        public async Task<IActionResult> List()
        {
            IEnumerable<BeerDTO> beers = await _service.GetAllBeersAsync();

            if (beers == null)
            {
                return NotFound();
            }

            BeerFilterList beerFilterList = new BeerFilterList
            {
                ListBeers = beers,
                FilterCriteria = null
            };

            ViewData["Countries"] = new SelectList(_countryService.GetAllCountries().OrderBy(x => x.Name), "Id", "Name");
            ViewData["Styles"] = new SelectList(_styleService.GetAllStyles().Result.OrderBy(x => x.Name), "Id", "Name");

            return View(beerFilterList);
        }

        // Post: List
        [HttpPost("/List")]
        public async Task<IActionResult> List([Bind("Country,Style")] FilterCriteria filterCriteria)
        {
            if (ModelState.IsValid)
            {
                var filteredCountry = filterCriteria.Country;
                var filteredStyle = filterCriteria.Style;
                IEnumerable<BeerDTO> beers = await _service.FilterBeersWebAsync(filteredCountry, filteredStyle);
                BeerFilterList beerFilterList = new BeerFilterList
                {
                    ListBeers = beers,
                    FilterCriteria = filterCriteria
                };

                ViewData["Countries"] = new SelectList(_countryService.GetAllCountries().OrderBy(x => x.Name), "Id", "Name");
                ViewData["Styles"] = new SelectList(_styleService.GetAllStyles().Result.OrderBy(x => x.Name), "Id", "Name");

                return View(beerFilterList);
            }

            return RedirectToAction(nameof(List));
        }

        // GET: Beers/Details/5
        [HttpGet("/Details/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _service.GetBeerByIdAsync(id.Value);
            if (beer == null)
            {
                return NotFound();
            }

            beer.BreweryName = _breweryService.GetBreweryAsync(beer.BreweryId).Result.Name;
            beer.StyleName = _styleService.GetStyleAsync(beer.StyleId).Result.Name;
            var beerViewModel = (BeerViewModel)_mapper.Map(beer, typeof(BeerDTO), typeof(BeerViewModel));
            
            beerViewModel.Rating = _service.GetBeerRatingAsync(id.Value).Result;

            var beerReviewsDTO = _reviewService.GetBeerReviewsAsync(id.Value).Result;
            beerViewModel.BeerReviews = new List<BeerReview>();

            if (beerReviewsDTO != null)
            {
                foreach (var review in beerReviewsDTO)
                {
                    BeerReview beerReview = new BeerReview() { BeerId = review.BeerId, UserId = review.UserId, Id = review.Id, Review = review.Review, Likes = review.Likes };
                    beerViewModel.BeerReviews.Add(beerReview);
                }
            }

            if (TempData["Success"] != null)
            {
                beerViewModel.ShowSuccessMessage = (bool)TempData["Success"];
            }

            return View(beerViewModel);
        }

        // GET: Beers/Create
        [HttpGet("/Create")]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Create()
        {
            ViewData["BreweryId"] = new SelectList(_breweryService.GetAllBreweries().Result, "Id", "Name");
            ViewData["StyleId"] = new SelectList(_styleService.GetAllStyles().Result, "Id", "Name");
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,ABV,BreweryId,Description,StyleId")] BeerDTO beer)
        {
            if (ModelState.IsValid)
            {
                BeerDTO resultBeerDTO = await _service.CreateBeerAsync(beer);
                return RedirectToAction(nameof(List));
            }
            return View();
        }

        //GET: Beers/Edit/5
        [HttpGet("/Edit")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _service.GetBeerByIdAsync(id.Value);
            if (beer == null)
            {
                return NotFound();
            }
            
            ViewData["BreweryId"] = new SelectList(_breweryService.GetAllBreweries().Result, "Id", "Name", beer.BreweryId);
            ViewData["StyleId"] = new SelectList(_styleService.GetAllStyles().Result, "Id", "Name", beer.StyleId);
            return View(beer);
        }

        //POST: Beers/Edit/5
        [HttpPost("/Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ABV,BreweryId,Description,StyleId")] BeerDTO beer)
        {
            if (id != beer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    BeerDTO resultBeerDTO = await _service.UpdateBeerAsync(beer.Id, beer);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeerExists(beer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(List));
            }

            return RedirectToAction(nameof(List));
        }

        // GET: Beers/Delete/5
        [HttpGet("/Delete/{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _service.GetBeerByIdAsync(id.Value);

            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // POST: Beers/Delete/5
        [HttpPost("/DeleteConfirmed"), ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var beer = await _service.DeleteBeerAsync(id);
            return RedirectToAction(nameof(List));
        }

        private bool BeerExists(int id)
        {
            if(_service.GetBeerByIdAsync(id) != null)
            {
                return true;
            }

            return false;
        }

        // GET: Beers/Unlist/5
        [HttpGet("/Unlist/{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Unlist(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _service.GetBeerByIdAsync(id.Value);

            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // POST: Beers/Unlist/5
        [HttpPost("/UnlistConfirmed"), ActionName("UnlistConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnlistConfirmed(int id)
        {
            var beer = await _service.UnlistBeerAsync(id);
            return RedirectToAction(nameof(List));
        }

        //POST: Beers/RateBeer
        [HttpPost("/RateBeer"), ActionName("RateBeer")]
        [Authorize(Roles = "Admin, User")]
        public async Task<IActionResult> RateBeer(int beerId, int rating)
        {
            var currentUser = _userManager.GetUserAsync(User).Result;

            var beerRatingDTO = new BeerRatingDTO
            {
                UserId = currentUser.Id,
                BeerId = beerId,
                Rating = rating

BeerOverflow/BeerOverflow/Controllers/BreweryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeerOverflow.Data.Models;
using BeerOverflow.Models;
using BeerOverflow.Service.Contracts;
using BeerOverflow.Service.DTO;
using Microsoft.AspNetCore.Mvc;

namespace BeerOverflow.Controllers
{
    public class BreweryController : Controller
    {
        private readonly IBreweryService _service;

        public BreweryController(IBreweryService service)
        {
            this._service = service;
        }

        public async Task<IActionResult> Index()
        {
            var list = await _service.GetAllBreweries();

            return View(list);
        }

        public async Task<IActionResult> Details(int id)
        {
            var brewery = await _service.GetBreweryAsync(id);

            return View(brewery);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BreweryDTO breweryDTO)
        {
            var brewery = await _service.CreateBreweryAsync(breweryDTO);

            return Redirect("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brewery = await _service.GetBreweryAsync((int)id);

            return View(brewery);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name,CountryId")] BreweryDTO breweryDTO)
        {
            var brewery = await _service.UpdateBreweryAsync(breweryDTO);

            return View("Details",brewery);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var dto = await _service.GetBreweryAsync((int)id);
            
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([Bind("Id")] BreweryDTO breweryDTO)
        {
            await _service.DeleteBreweryAsync((int)breweryDTO.Id);

            return RedirectToAction("Index");
        }
    }
}

BeerOverflow/BeerOverflow/Controllers/StyleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeerOverflow.Service.Contracts;
using BeerOverflow.Service.DTO;
using Microsoft.AspNetCore.Mvc;

namespace BeerOverflow.Controllers
{
    public class StyleController : Controller
    {
        private readonly IStyleService _service;

        public StyleController(IStyleService service)
        {
            this._service = service;
        }

        public async Task<IActionResult> Index()
        {
            var list = await _service.GetAllStyles();

            return View(list);
        }

        public async Task<IActionResult> Details(int id)
        {
            var style = await _service.GetStyleAsync(id);

            return View(style);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StyleDTO styleDTO)
        {
            var style = await _service.CreateStyleAsync(styleDTO);

            return Redirect("Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var style = await _service.GetStyleAsync((int)id);

            return View(style);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name")] StyleDTO styleDTO)
        {
            var style = await _service.UpdateStyleAsync(styleDTO);

            return View("Details", style);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var dto = await _service.GetStyleAsync((int)id);

            return View(dto);
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete([Bind("Id")] StyleDTO styleDTO)
        {
            await _service.DeleteStyleAsync((int)styleDTO.Id);

            return RedirectToAction("Index");
        }
    }
}

BeerOverflow/BeerOverflow/Controllers/UserMenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeerOverflow.Data.Context;
using BeerOverflow.Data.Models;
using BeerOverflow.Service.Contracts;
using BeerOverflow.Service.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BeerOverflow.Controllers
{
    public class UserMenuController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IUserService _service;

        public UserMenuController(UserManager<User> manager, IUserService service)
        {
            this.userManager = manager;
            _service = service;
        }

        public async Task<IActionResult> MyWishlist()
        {
            var user = await userManager.GetUserAsync(User);

            var list = _service.GetWishlist(user.Id);

            return View(list);
        }

        public async Task<IActionResult> MyDranklist()
        {
            var user = await userManager.GetUserAsync(User);

            var list = _service.GetDranklist(user.Id);

            return View(list);
        }

        public async Task<IActionResult> MyStatus()
        {
            var user = await userManager.GetUserAsync(User);

            return View(user);
        }
    }
}

BeerOverflow/BeerOverflow/Views/Shared/_BeerCardPartial.cshtml
@model BeerViewModel

<div class="col-md-4">
    <img src="~/images/5.jpg" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.ABV</p>
        <a asp-area="" asp-controller="Beers" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">Find out more</a>
    </div>
</div>

BeerOverflow/BeerOverflow/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeerOverflow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/navbar.css" />
    <link rel="stylesheet" href="~/css/datatable.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <header>
        <div style="height:75px">
            <nav style="background-color:black" class="navbar navbar-expand-lg navbar-light fixed-top">
                <a class="navbar-brand" href="#">BEEROVERFLOW</a>
                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="hoverable">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="hoverable">
                                <a class="nav-link" asp-area="" asp-controller="Beers" asp-action="List">Beers</a>
                            </li>
                            <li class="hoverable">
                                <a class="nav-link" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                            </li>
                            <li class="hoverable">
                                <a class="nav-link" asp-area="" asp-controller="Brewery" asp-action="Index">Breweries</a>
                            </li>
                            <li class="hoverable">
                                <a class="nav-link" asp-area="" asp-controller="Style" asp-action="Index">Styles</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            @if (SignInManager.IsSignedIn(User))
                            {

                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="hoverable">
                                        <a class="nav-link " id="register" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                    </li>
                                }

                                @if (User.Identity.IsAuthenticated)//@if (User.IsInRole("User"))
                                    {
                                        <li class="dropdown hoverable">
                                            <a asp-controller="Home"
                                               class="nav-link " data-toggle="dropdown">Hello, @User.Identity.Name!<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a class="nav-link text-dark" asp-controller="UserMenu" asp-action="MyWishlist">My Wishlist</a>
                                                </li>
                                                <li>
                                                    <a class="nav-link text-dark" asp-controller="UserMenu" asp-action="MyDranklist">My Dranklist</a>
                                                </li>
                                                <li>
                                                    <a class="nav-link text-dark" asp-controller="UserMenu" asp-action="MyStatus">My Status</a>
                                                </li>
                                            </ul>
                                        </li>
                                    }

                                <li class="hoverable">
                                    <a id="logout" class="nav-link" asp-controller="Users" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="hoverable">
                                    <a class="nav-link " id="register" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
                                </li>
                                <li class="hoverable">
                                    <a class="nav-link " id="login" asp-controller="Users" asp-action="Login">Login</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div style="height:50px"></div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BeerOverflow - Telerik Academy Project<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>